### ISSUE TITLE
Test option2 in Puzzle1 is failed since 'Element not found {div/a}'.

### ISSUE THREAD

**Issue by clobob** [asolntsev/selenide-puzzlers#58]
Try run test Puzzle1.java with Junit in Eclipse.

```
  @Test
  public void option2() {
    $("div").$("a").click();
  }
```

Actual result: Test failed.

Here is Failure Trace: 
```
Element not found {div/a}
Expected: text 'ya.ru'
Screenshot: file:/F:/work_opensources/selenide-puzzlers/build/reports/tests/1626169588354.0.png
Page source: file:/F:/work_opensources/selenide-puzzlers/build/reports/tests/1626169588354.0.html
Timeout: 4 s.
Caused by: NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"a"}
	at com.codeborne.selenide.impl.WebElementSource.createElementNotFoundError(WebElementSource.java:83)
	at org.selenide.puzzlers.Puzzle1.option2(Puzzle1.java:24)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"a"}
```

JDK: 1.8
Eclipse: 2020-06
Gradle: 6.6.1
This project: latest
Browser: chrome 69.0.3497.92

**Comment by asolntsev** [comment]
@clobob Yes, it's the expected result.
The whole point of puzzles is to guess what happens: either the test works or fails. That test should fail.
